os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.1 
script:
  - swift package clean
  - swift package update
  - swift build
  - swift test -Xswiftc -DCI_BUILD
notifications:
  email:
    on_success: never
    on_failure: change
